# Generated by Django 4.0.2 on 2022-05-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rankdata',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rankdata', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'rankdata',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('workarea', models.CharField(max_length=25)),
                ('id', models.CharField(db_column='ID', max_length=20)),
                ('pass_field', models.CharField(db_column='pass', max_length=20)),
                ('rno', models.ForeignKey(db_column='rno', on_delete=django.db.models.deletion.DO_NOTHING, to='zerofire.rankdata')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
